### ISSUE TITLE
Sprite Editor Crashes when trying to import as color.

### ISSUE THREAD

**Issue by resistthis13** [ProgSys/pg_disatools#10] opened 2016-10-12 20:14 UTC
I'm not sure if something's wrong with the file I'm trying to edit, or the image I'm trying to import. I increased the color size, and as soon as it asks me to add the colors it crashes. I'm trying to use 1110_MAGE.SH as a base to make a sprite for Artina (or Vulcanus as she calls herself in Disgaea 4).
I'll attach both files to see if maybe you could figure out what the issue is?

![artina1](https://cloud.githubusercontent.com/assets/10591265/19326041/d442578c-9096-11e6-9d98-83b971d7b389.png)

https://drive.google.com/open?id=0Bw-WsMYQKRQuMjZ5X0JzVWFSSUk

I've tried other files, the other edit I mentioned of replacing Laharl's sprite with it's Disgaea 2 counterpart gave me no problems.

**Comment by ProgSys** [comment] 2016-10-13 18:03
I can reproduce the problem. The issue is that if you make/change/import a sprite with _n_-colors than the color table should also have at least  _n_-colors, if it isn't then it can cause a crash. I will make it more robust and also make the color table resize automatectly.

In the mean time you can just increase the size of the color table to at least 255 colors in the color table view, before you import the sprite.

**Comment by resistthis13** [comment] 2016-10-13 20:45
Do you mean changing the color offset? Because I did actually change the size to 255 in the menu that pops up when the gear icon is clicked. The sprite replacer only said it has 100 something colors. 

Unless you mean something else I'm not seeing there?

**Comment by ProgSys** [comment] 2016-10-13 21:15
I mean you can change the size of the color table manually:
![colortable](https://cloud.githubusercontent.com/assets/4257741/19367270/b10b935a-919a-11e6-80a1-a5c64338cc97.png)

But I released a new version (v0.7.3) in which your bugs should be fixed now.

**Comment by resistthis13** [comment] 2016-10-14 01:07
Ah I didn't know exactly how to do that, but thanks.

**Closed as completed** 2016-10-15 09:23 UTC
Labels: bug
