### ISSUE TITLE
Unable to import edited sprite to sprite sheet editor

### ISSUE THREAD

**Issue by Pacmega** [ProgSys/pg_disatools#7] opened 2016-09-15 17:09 UTC
Hi, it's Adriaan from the Steam forum again. First of all, massive thanks for linking me to here! I managed to get through almost all of the steps you described without too much of an issue, and I'm close to making my first changes to existing sprites thanks to you! :D

However, there is one issue I ran into. When trying to import an edited image to the sprite sheet editor I get the error "Given color image has more colors than the sprite sheet supports! (16)", but I don't understand why this is. I have made certain that the image is saved uncompressed and I don't add any new colors to it, but there are still too many colors somehow. To test if I had made a mistake I also tried exporting an image and immediate importing that same (unchanged) image again, and that seems to trigger the same issue. So even the original sprites for the Martial Artist (1010_BRAWLER_MALE.SH is the file I'm using) can not be imported back into the same sheet. I don't see what the problem is here, perhaps you could enlighten me?

Thanks in advance!

**Comment by ProgSys** [comment] 2016-09-15 19:47
Sorry, it was a bug, I fixed it and released a new version. 
Let me know it it is working now.

Basically it triggered the error message when the amount of colors was the same as the maximum number of colors allowed on the sprite sheet. Stupid mistake.

**Comment by Pacmega** [comment] 2016-09-16 07:36
Looks like everything is working as intended now! I haven't managed to get my changes to be visible in game yet, but that's probably because I'm not doing something right there.

Either way, the editor is working correctly now!

**Comment by ProgSys** [comment] 2016-09-16 08:35
Well if you need help just ask.

**Comment by Pacmega** [comment] 2016-09-16 08:55
Will do! I'm at school right now though, so it'll be a while until I'll be able to really continue testing... But once I get back I'll see if I can get it to work properly.

**Comment by Pacmega** [comment] 2016-09-16 16:44
Alright, back at my PC again and things seem to be a bit odd. When I attempt to save a .DAT file on my PC, the file manager crashes. Even without changing it, when I click "save as" the application simply stops working and Windows shuts it down. While on my laptop the same version works fine...

In the meantime I still haven't managed to get things working properly on my laptop. I can now edit and import sprites like I should, and according to the sprite sheet editor (v0.2.7) animations should be changed appropriately. The previews it shows of animations of both the Martial Artist and Laharl should be changed when I push my edited versions, but when I do so and import the files all the way to SUBDATA and run the game nothing has changed. I don't understand what the issue is...

**Comment by ProgSys** [comment] 2016-09-16 17:02
The main character animations are inside `SUBDATA.DAT\START.DAT\ANM00.DAT` make sure that you replaced your file and not insert a new one.

![img](https://dl.dropboxusercontent.com/u/33065226/disgaea/wiki/HD%20sprite%20tutorial/replace_old.png)

You can test it by opening the file directly through the file manager.
Also make sure that you replaced a animation that is used in game. There are some animations that look the same, but are for different weapons. 

I heard about the crash bug, but I couldn't replicate it on my systems. Can you maybe tell be what operating system your system uses? Do you see the save file dialog or does it crash immediately?

**Comment by Pacmega** [comment] 2016-09-16 18:30
I followed the exact steps you described on the wiki, indeed including to replace and keep the name instead of inserting a new one. How is it possible to open a file through the file manager? The only way I've found to look inside files is to extract them and then open them. 

Regarding ANM.DAT, is it possible that the name is ANM00.DAT instead of that? Because I can only find that name inside START.DAT, there doesn't seem to be an ANM without any numbers anywhere. Within ANM00 I did find the sprites I am looking for, but to give you an idea of what I edited here is a screenshot of my "product". What you can see in the screenshot is page 1 (or according to the editor page 0) is as far as I'm aware all of Laharl's walking and standing animations, which should after inserting my sheet into the files change to him sliding around on the floor. However, in game he doesn't actually wear my sunglasses, or float around... Or do anything I tried to do really. Same goes for the Martial Artist, he still doesn't seem to want to change either.

![ripwalking](https://cloud.githubusercontent.com/assets/7987979/18596620/5f796b58-7c4a-11e6-8aea-987799a4757d.png)

In regards to the crash bug: both my laptop and my PC run Windows 7, but my laptop runs Win7 Ultimate whereas my PC runs Home edition. As soon as I click either "Save" or "Save as" the program crashes and I get the Windows screen showing a program has crashed. Perhaps there is a crash log somewhere that I could share, but I've so far been unable to find it.

**Comment by ProgSys** [comment] 2016-09-16 18:58
Yes, you are right it is `AMN00.DAT` and your modded version should work. If you replace it it should display it ingame.
The _Open_ button is in the same menu as _Replace_:
![open_img](https://dl.dropboxusercontent.com/u/33065226/disgaea/open_sprite.png)

I updated the [latest version](https://drive.google.com/file/d/0B_RzJQb1tHO_clNYNHpaY2E4VlE/view?usp=sharing), maybe I fixed the crash, but I am not sure. I will need to do some testing to find out what is going on. It seams to do something with the windows version.

**Comment by Pacmega** [comment] 2016-09-16 20:00
Yeah, it does seem likely that the crash is related to the Windows version. I'll test it on another laptop around here with Win7 Ultimate and will report back how that works, if it works there chances are that it just doesn't work on the Home edition. I'll also try out opening and changing the sprite on that laptop, perhaps I'll have better results now that I know what I'm looking for (and where the _open_ button is)

I have no idea how I managed to miss the _open_ button so many times... But thanks for pointing it out, that makes seeing if it works a lot easier! :stuck_out_tongue_winking_eye: 

Update 1: Nope, doesn't seem like the update fixed the crash for my PC. We can't be sure yet that it's because of the Windows version or because I don't have some prerequisite installed here that I do have on my laptop, but I'll test on more devices and see how that goes!

Update 2: Using the newest version (which doesn't seem to have been pushed to the github repo yet, but considering that it doesn't seem to fix the issue that doesn't seem like much use anyway :P) and on a different laptop which also uses Win7 Ultimate, and the crash is still present. It seems to be exactly the same, the moment I click save the program crashes without any further information.
Something else that I discovered also causes the program to crash (present in the previous version as well): right clicking a file and opening file info works fine, but when I try to close file info the program closes file info, but crashes after doing so.

**Comment by Pacmega** [comment] 2016-09-16 21:43
Okay, I found something odd while looking around with the File Manager on my laptop. Importing ANM00.DAT into START.DAT goes just fine, as does opening START.DAT and reopening ANM00 from there. But from START things go south. I tried using "Save As" on START to create a clone of it, but the clone isn't actually a clone.

The cloned version of the archive contains a list of FILExxxx.DAT (xxxx being a number) instead of the original named archives, and all of the .TX2 items have been changed to be FILExxxx.TX2 files. The TX2 files do still contain the same images, but because the names all got messed up the files are most likely out of order. I'm not sure what is causing it, but after cloning it multiple times the same issue kept occuring.

One thing to keep in mind with this observation though: I have only been able to test this on one computer. This does seem to explain why my changes aren't being applied to the game when they should, but I have no clue what could be the cause of this...

**Comment by ProgSys** [comment] 2016-09-16 22:12
Well the naming thing is easy to explain, the files inside `START` actually don't have any names at all. It is just a list of data. The File Menager names them, based on some files found in the PSP version, to make it easier to navigate. The problem is, there are many other _.DAT_ files, so as soon you change the name it dosn't know anymore that it is a _START_ file and dosn't name them.
But I probably should make it so, that files which begin with `START`, like `STARTrandomestring.DAT` still get named.

The names of the files are defined inside `resources/START.DAT.csv`

**Comment by ProgSys** [comment] 2016-09-16 22:45
I made a gif with all the steps you need to do to import it:
![gif](https://dl.dropboxusercontent.com/u/33065226/disgaea/import_laharl.gif)

**Comment by Pacmega** [comment] 2016-09-17 08:48
Looks like I did everything right then. I don't know why, but the version on my laptop just does not seem to want to accept changes... Also it seems that right now, whenever I try to extract START.DAT from SUBDATA I get a file that the file manager refuses to open. I wish I could record what is happening on my end, but since it happens on my laptop I don't really have any way of doing so... I could look into it though, pehaps that would help?

Another thing I want to mention is that on my laptop the game doesn't seem to be working entirely correct either way. Since there is no floor... I'm not sure what went wrong, but the version I'm running there seems to be a bit broken somehow.

**Comment by ProgSys** [comment] 2016-09-17 10:18
[Redownlaod version 0.6.3](https://drive.google.com/file/d/0B_RzJQb1tHO_dk84aWItLVVlMFk/view?usp=sharing), I think I found the problem for the crash.

You need to decompress `START.DAT`:
![img](https://dl.dropboxusercontent.com/u/33065226/disgaea/decompress.png)

**Comment by Pacmega** [comment] 2016-09-17 15:13
Alright, after testing I can conclude that I can now save normally on my PC! So that bug has indeed been fixed! And I'm not sure why my laptop kept ignoring all the changes I made, because now when I follow your steps everything works! I can now properly use my changes sprites in game, so it's time for me to get to work on producing something of a bit higher quality than I have so far :P

However, the file manager doesn't seem to be entirely bug free yet. One thing that also triggered the crash was trying to look at file info and closing it afterwards, which has now been changed to the program crashing as soon as I click "File info" on anything. However, saving works consistently now so that part is solved!

I have no idea how I managed to mess up the decompressing... I've done it at least a dozen times in the past day, so why I suddenly forgot about it is something I don't understand. >.<

**Comment by ProgSys** [comment] 2016-09-17 15:39
Nice at least now saving works. 😄  Will look into the file info crash now, I already kinda have a idea why it is happening.

**Comment by ProgSys** [comment] 2016-09-17 19:20
The info box crash should now be fixed in the new version (v0.6.4).

**Comment by Pacmega** [comment] 2016-09-17 20:50
Yep, looks like that is now fixed as well! I can open it without problems, and closing it doesn't cause a crash anymore either.

**Closed as completed** 2016-09-19 07:09 UTC
Labels: bug, help wanted
